### PR TITLE
costumes/:id displays show page with costume show card

### PR DESCRIPTION
**Pull request by Wallace-A**
- costumes/:id displays costume show page
- created show page.html.erb
- created costume_show_card.html.erb
- created costume_show_card.scss
- It's just the le wagon trip card
-
Screenshot from 2021-02-22 20-30-30

### CODE REVIEW

**Comment by blamb888** [comment]
Thanks for that Andrew. The links are working alright then? I'll get to work on the partial today. Might change some elements to fit the form.

**Review by blamb888 — COMMENTED** [review]
Looks good under the hood.

**Comment by blamb888** [comment]
Okay I think this will close the 'review required' I think when I hit the "close with comment" button?

**Comment by Wallace-A** [comment]
what links do you mean?

**Comment by blamb888** [comment]
The links in the navbar back to home.

**Comment by blamb888** [comment]
Do we need everyone to review this before someone other than me can merge the pull request? Is that what this means?
image

**Comment by blamb888** [comment]
Does this satisfy the request

**Review by blamb888 — APPROVED** [review]
Does this work?

**Pull request merged**
